// Form definitions for the CMS. Every key in shared/defaultContent.json → settings must appear here
// (checked by scripts/check-cms-schema.mjs), so nothing shown on the website is left uneditable.
// Field types: text | textarea | number | image | list (strings) | stats ({value,label}) | links ({label,href})

export const SETTINGS_SECTIONS = [
  {
    key: 'site', title: 'General & SEO', desc: 'Browser tab title, Google description, and how prices are formatted.',
    fields: [
      { key: 'title', label: 'Page title (browser tab)', type: 'text' },
      { key: 'meta_description', label: 'SEO description (meta description)', type: 'textarea', help: 'About 150 characters. Leave empty if not needed.' },
      { key: 'locale', label: 'Number format (locale)', type: 'text', help: 'e.g. en-US → 1,234.50 · vi-VN → 1.234,5' },
      { key: 'currency_code', label: 'Currency code', type: 'text', help: 'ISO code used for all prices, e.g. USD, EUR, VND. Prices under "Services & pricing" are entered in this currency.' },
    ],
  },
  {
    key: 'brand', title: 'Brand', desc: 'Name shown in the logo in the navigation bar and footer.',
    fields: [
      { key: 'name_part1', label: 'Name – part 1 (white)', type: 'text' },
      { key: 'name_part2', label: 'Name – part 2 (green)', type: 'text' },
      { key: 'tagline', label: 'Tagline under the logo', type: 'text' },
    ],
  },
  {
    key: 'nav', title: 'Menu (navigation bar)', desc: 'Menu labels on desktop and mobile.',
    fields: [
      { key: 'about', label: 'Desktop – About', type: 'text' },
      { key: 'services', label: 'Desktop – Services', type: 'text' },
      { key: 'calculator', label: 'Desktop – Quote tool', type: 'text' },
      { key: 'portfolio', label: 'Desktop – Projects', type: 'text' },
      { key: 'testimonials', label: 'Desktop – Reviews', type: 'text' },
      { key: 'contact', label: 'Desktop – Contact', type: 'text' },
      { key: 'cta', label: 'Desktop – Quote button', type: 'text' },
      { key: 'mobile_about', label: 'Mobile – About', type: 'text' },
      { key: 'mobile_services', label: 'Mobile – Services', type: 'text' },
      { key: 'mobile_calculator', label: 'Mobile – Quote tool', type: 'text' },
      { key: 'mobile_portfolio', label: 'Mobile – Projects', type: 'text' },
      { key: 'mobile_testimonials', label: 'Mobile – Reviews', type: 'text' },
      { key: 'mobile_contact', label: 'Mobile – Contact', type: 'text' },
      { key: 'mobile_cta', label: 'Mobile – Quote button', type: 'text' },
    ],
  },
  {
    key: 'hero', title: 'Hero banner', desc: 'The first area visitors see, including the site visit booking card.',
    fields: [
      { key: 'background_image', label: 'Background image', type: 'image', help: 'Landscape photo, 1920–2560 px wide, ideally under 500 KB. Upload here or paste a URL.' },
      { key: 'background_position', label: 'Background focus point', type: 'text', help: 'Which part of the photo stays visible on narrow screens: center, top, bottom, left, right, or e.g. "center 70%".' },
      { key: 'overlay_strength', label: 'Overlay strength (0–100)', type: 'number', help: 'How dark the green overlay is. 0 = photo only; 80 = default; raise it if the text is hard to read.' },
      { key: 'badge', label: 'Small label above the title', type: 'text' },
      { key: 'title_line1', label: 'Title – line 1', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'title_line2', label: 'Title – ending', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'value_props', label: 'Key selling points (check marks)', type: 'list' },
      { key: 'cta_primary', label: 'Primary button', type: 'text' },
      { key: 'cta_secondary', label: 'Secondary button', type: 'text' },
      { key: 'stats', label: 'Statistics', type: 'stats' },
      { key: 'form_title', label: 'Booking card – title', type: 'text' },
      { key: 'form_subtitle', label: 'Booking card – subtitle', type: 'text' },
      { key: 'form_service_label', label: 'Booking card – service label', type: 'text', help: 'The service list comes from "Services & pricing" (field "Hero label").' },
      { key: 'form_phone_label', label: 'Booking card – phone label', type: 'text' },
      { key: 'form_phone_placeholder', label: 'Booking card – phone placeholder', type: 'text' },
      { key: 'form_submit', label: 'Booking card – submit button', type: 'text' },
      { key: 'form_submitting', label: 'Booking card – text while sending', type: 'text' },
      { key: 'trust_left', label: 'Trust line – left', type: 'text' },
      { key: 'trust_right', label: 'Trust line – right', type: 'text' },
    ],
  },
  {
    key: 'about', title: 'About us section', desc: 'Company introduction below the hero banner. The "About us" menu label is edited under Menu.',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'paragraph1', label: 'Paragraph 1', type: 'textarea' },
      { key: 'paragraph2', label: 'Paragraph 2', type: 'textarea' },
      { key: 'highlights', label: 'Highlights (check marks)', type: 'list' },
      { key: 'stats', label: 'Statistics (3 boxes)', type: 'stats' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'image_alt', label: 'Image description (alt text)', type: 'text' },
    ],
  },
  {
    key: 'services_section', title: 'Services – heading', desc: 'Heading of the Services section. Each service is edited under "Services & pricing".',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'price_format', label: 'Price display template', type: 'text', help: '{price} is replaced with the unit price. e.g. From {price} / sq ft' },
      { key: 'card_button', label: 'Service card button', type: 'text' },
    ],
  },
  {
    key: 'calculator', title: 'Quote calculator', desc: 'Text and settings of the cost estimator. Prices & discounts are edited under "Services & pricing" and "Frequency & discounts".',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'step1_title', label: 'Step 1 – title', type: 'text' },
      { key: 'service_label', label: 'Service label', type: 'text' },
      { key: 'area_label', label: 'Area label', type: 'text' },
      { key: 'area_unit', label: 'Area unit', type: 'text' },
      { key: 'area_min', label: 'Minimum area', type: 'number' },
      { key: 'area_max', label: 'Maximum area', type: 'number' },
      { key: 'area_step', label: 'Slider step', type: 'number' },
      { key: 'area_default', label: 'Default area', type: 'number' },
      { key: 'area_hint_min', label: 'Slider caption – left', type: 'text' },
      { key: 'area_hint_mid', label: 'Slider caption – middle', type: 'text' },
      { key: 'area_hint_max', label: 'Slider caption – right', type: 'text' },
      { key: 'frequency_label', label: 'Frequency label', type: 'text' },
      { key: 'summary_service', label: 'Summary – service', type: 'text' },
      { key: 'summary_rate', label: 'Summary – rate', type: 'text' },
      { key: 'summary_rate_format', label: 'Summary – rate template', type: 'text', help: '{rate} = unit price' },
      { key: 'summary_discount', label: 'Summary – discount', type: 'text' },
      { key: 'summary_standard', label: 'Summary – when there is no discount', type: 'text' },
      { key: 'summary_discount_format', label: 'Summary – discount template', type: 'text', help: '{pct} = discount %' },
      { key: 'total_label', label: 'Total label', type: 'text' },
      { key: 'total_note', label: 'Total note', type: 'text' },
      { key: 'currency', label: 'Text after the total (optional)', type: 'text', help: 'The total already shows the currency symbol; leave empty unless you want extra text.' },
      { key: 'step2_title', label: 'Step 2 – title', type: 'text' },
      { key: 'name_label', label: 'Name label', type: 'text' },
      { key: 'name_placeholder', label: 'Name placeholder', type: 'text' },
      { key: 'phone_label', label: 'Phone label', type: 'text' },
      { key: 'phone_placeholder', label: 'Phone placeholder', type: 'text' },
      { key: 'email_label', label: 'Email label', type: 'text' },
      { key: 'email_placeholder', label: 'Email placeholder', type: 'text' },
      { key: 'date_label', label: 'Site visit date label', type: 'text' },
      { key: 'address_label', label: 'Address label', type: 'text' },
      { key: 'address_placeholder', label: 'Address placeholder', type: 'text' },
      { key: 'notes_label', label: 'Notes label', type: 'text' },
      { key: 'notes_placeholder', label: 'Notes placeholder', type: 'text' },
      { key: 'submit', label: 'Submit button', type: 'text' },
      { key: 'submitting', label: 'Text while sending', type: 'text' },
      { key: 'success_message', label: 'Success message', type: 'textarea', help: '{id} = quote number' },
      { key: 'error_required', label: 'Error – missing information', type: 'text' },
      { key: 'error_failed', label: 'Error – request failed', type: 'text' },
      { key: 'error_network', label: 'Error – connection lost', type: 'text' },
    ],
  },
  {
    key: 'portfolio', title: 'Projects – heading & before/after', desc: 'Heading and the before/after image slider. Project cards are edited under "Projects".',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'legend_before', label: '"Before" caption', type: 'text' },
      { key: 'legend_after', label: '"After" caption', type: 'text' },
      { key: 'before_image', label: 'BEFORE image', type: 'image' },
      { key: 'before_alt', label: 'BEFORE image description (alt)', type: 'text' },
      { key: 'before_badge', label: 'Label on BEFORE image', type: 'text' },
      { key: 'after_image', label: 'AFTER image', type: 'image' },
      { key: 'after_alt', label: 'AFTER image description (alt)', type: 'text' },
      { key: 'after_badge', label: 'Label on AFTER image', type: 'text' },
      { key: 'hint', label: 'Hint under the image', type: 'text' },
    ],
  },
  {
    key: 'testimonials_section', title: 'Reviews – heading', desc: 'Heading of the Reviews section. Each review is edited under "Customer reviews".',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'contact', title: 'Contact section', desc: 'Office details and the message form.',
    fields: [
      { key: 'badge', label: 'Small label', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'title_highlight', label: 'Title – highlighted part', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'office_title', label: 'Info box title', type: 'text' },
      { key: 'address_label', label: 'Address label', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'hotline_label', label: 'Hotline label', type: 'text' },
      { key: 'hotline_text', label: 'Hotline (displayed text)', type: 'text' },
      { key: 'hotline_tel', label: 'Hotline (number to dial)', type: 'text', help: 'Digits only, e.g. 5551234567' },
      { key: 'email_label', label: 'Email label', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'hours_label', label: 'Business hours label', type: 'text' },
      { key: 'hours', label: 'Business hours', type: 'text' },
      { key: 'form_title', label: 'Form – title', type: 'text' },
      { key: 'name_label', label: 'Form – name label', type: 'text' },
      { key: 'name_placeholder', label: 'Form – name placeholder', type: 'text' },
      { key: 'phone_label', label: 'Form – phone label', type: 'text' },
      { key: 'phone_placeholder', label: 'Form – phone placeholder', type: 'text' },
      { key: 'email_field_label', label: 'Form – email label', type: 'text' },
      { key: 'email_placeholder', label: 'Form – email placeholder', type: 'text' },
      { key: 'message_label', label: 'Form – message label', type: 'text' },
      { key: 'message_placeholder', label: 'Form – message placeholder', type: 'text' },
      { key: 'submit', label: 'Form – submit button', type: 'text' },
      { key: 'submitting', label: 'Form – text while sending', type: 'text' },
      { key: 'success_message', label: 'Success message', type: 'text' },
      { key: 'error_required', label: 'Error – missing information', type: 'text' },
      { key: 'error_network', label: 'Error – connection lost', type: 'text' },
    ],
  },
  {
    key: 'footer', title: 'Footer', desc: 'The "Main services" list comes from "Services & pricing" (field "Footer label").',
    fields: [
      { key: 'about', label: 'Short introduction', type: 'textarea' },
      { key: 'copyright', label: 'Copyright line', type: 'text' },
      { key: 'services_title', label: 'Services column title', type: 'text' },
      { key: 'links_title', label: 'Links column title', type: 'text' },
      { key: 'links', label: 'Quick links', type: 'links' },
      { key: 'support_title', label: 'Support column title', type: 'text' },
      { key: 'phone', label: 'Phone number', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'address', label: 'Address', type: 'text' },
      { key: 'bottom_note', label: 'Bottom line', type: 'text' },
      { key: 'back_to_top', label: 'Back to top button', type: 'text' },
    ],
  },
];

export const COLLECTIONS = {
  services: {
    title: 'Services & pricing',
    desc: 'Each service appears in 4 places: the Services cards, the quote calculator, the hero dropdown and the footer. Prices are shared by the website and the server.',
    itemTitle: (x) => x.title,
    itemSub: (x, money) => `${money(x.pricePerM2)} per unit · base fee ${money(x.basePrice)}`,
    empty: { slug: '', title: '', subtitle: '', description: '', pricePerM2: 0, basePrice: 0, icon: 'Scissors', image: '', features: [], calcName: '', heroEmoji: '', heroLabel: '', footerLabel: '', isActive: true },
    fields: [
      { key: 'slug', label: 'Service code (slug)', type: 'text', createOnly: true, help: 'a-z, 0-9 and hyphens. Used to store quotes; cannot be changed after creation.' },
      { key: 'title', label: 'Name (Services card)', type: 'text' },
      { key: 'subtitle', label: 'Subtitle (small line above)', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'pricePerM2', label: 'Unit price (per area unit, e.g. per sq ft)', type: 'number', help: 'In the site currency (General & SEO → Currency code). Decimals allowed, e.g. 0.02' },
      { key: 'basePrice', label: 'Base fee', type: 'number', help: 'Cost = (Base fee + Area × Unit price) × (100 − discount %) / 100, rounded to cents' },
      { key: 'icon', label: 'Icon', type: 'icon' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'features', label: 'Features (check marks)', type: 'list' },
      { key: 'calcName', label: 'Name in the quote calculator', type: 'text' },
      { key: 'heroEmoji', label: 'Hero emoji', type: 'text' },
      { key: 'heroLabel', label: 'Hero label', type: 'text' },
      { key: 'footerLabel', label: 'Footer label', type: 'text' },
      { key: 'isActive', label: 'Show on website', type: 'bool' },
    ],
  },
  'frequency-options': {
    title: 'Frequency & discounts',
    desc: 'Frequency options in the quote calculator and their discounts.',
    itemTitle: (x) => x.label,
    itemSub: (x) => (x.discountPct ? `${x.discountPct}% off` : 'Standard price'),
    empty: { label: '', discountPct: 0, hint: '', isActive: true },
    fields: [
      { key: 'label', label: 'Frequency name', type: 'text' },
      { key: 'discountPct', label: 'Discount %', type: 'number' },
      { key: 'hint', label: 'Small caption', type: 'text', help: 'Leave empty to hide.' },
      { key: 'isActive', label: 'Show on website', type: 'bool' },
    ],
  },
  projects: {
    title: 'Projects',
    desc: 'Project cards below the before/after slider.',
    itemTitle: (x) => x.title,
    itemSub: (x) => x.category,
    empty: { category: '', title: '', description: '', image: '', imageAlt: '', isActive: true },
    fields: [
      { key: 'category', label: 'Label (e.g. Lakeside villa)', type: 'text' },
      { key: 'title', label: 'Project name', type: 'text' },
      { key: 'description', label: 'Short description', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'imageAlt', label: 'Image description (alt)', type: 'text' },
      { key: 'isActive', label: 'Show on website', type: 'bool' },
    ],
  },
  testimonials: {
    title: 'Customer reviews',
    desc: 'Review cards in the "What our clients say" section.',
    itemTitle: (x) => x.name,
    itemSub: (x) => `${'★'.repeat(x.stars || 0)} · ${x.role || ''}`,
    empty: { name: '', role: '', content: '', stars: 5, avatar: '', isActive: true },
    fields: [
      { key: 'name', label: 'Customer name', type: 'text' },
      { key: 'role', label: 'Title / location', type: 'text' },
      { key: 'content', label: 'Review text', type: 'textarea' },
      { key: 'stars', label: 'Stars (1–5)', type: 'number' },
      { key: 'avatar', label: 'Profile photo', type: 'image' },
      { key: 'isActive', label: 'Show on website', type: 'bool' },
    ],
  },
};
