// Form definitions for the CMS. Every key in shared/defaultContent.json → settings must appear here
// (checked by scripts/check-cms-schema.mjs), so nothing shown on the website is left uneditable.
// Field types: text | textarea | number | image | list (strings) | stats ({value,label}) | links ({label,href})

export const SETTINGS_SECTIONS = [
  {
    key: 'site', title: 'Chung & SEO', desc: 'Tiêu đề tab trình duyệt và mô tả hiển thị trên Google.',
    fields: [
      { key: 'title', label: 'Tiêu đề trang (tab trình duyệt)', type: 'text' },
      { key: 'meta_description', label: 'Mô tả SEO (meta description)', type: 'textarea', help: 'Khoảng 150 ký tự. Để trống nếu chưa cần.' },
    ],
  },
  {
    key: 'brand', title: 'Thương hiệu', desc: 'Tên hiển thị ở logo Navbar và Footer.',
    fields: [
      { key: 'name_part1', label: 'Tên – phần 1 (màu trắng)', type: 'text' },
      { key: 'name_part2', label: 'Tên – phần 2 (màu xanh)', type: 'text' },
      { key: 'tagline', label: 'Dòng mô tả dưới logo', type: 'text' },
    ],
  },
  {
    key: 'nav', title: 'Menu (Navbar)', desc: 'Nhãn các mục menu trên máy tính và điện thoại.',
    fields: [
      { key: 'about', label: 'Máy tính – Về chúng tôi', type: 'text' },
      { key: 'services', label: 'Máy tính – Dịch vụ', type: 'text' },
      { key: 'calculator', label: 'Máy tính – Tính phí', type: 'text' },
      { key: 'portfolio', label: 'Máy tính – Dự án', type: 'text' },
      { key: 'testimonials', label: 'Máy tính – Đánh giá', type: 'text' },
      { key: 'contact', label: 'Máy tính – Liên hệ', type: 'text' },
      { key: 'cta', label: 'Máy tính – Nút báo giá', type: 'text' },
      { key: 'mobile_about', label: 'Điện thoại – Về chúng tôi', type: 'text' },
      { key: 'mobile_services', label: 'Điện thoại – Dịch vụ', type: 'text' },
      { key: 'mobile_calculator', label: 'Điện thoại – Tính phí', type: 'text' },
      { key: 'mobile_portfolio', label: 'Điện thoại – Dự án', type: 'text' },
      { key: 'mobile_testimonials', label: 'Điện thoại – Đánh giá', type: 'text' },
      { key: 'mobile_contact', label: 'Điện thoại – Liên hệ', type: 'text' },
      { key: 'mobile_cta', label: 'Điện thoại – Nút báo giá', type: 'text' },
    ],
  },
  {
    key: 'hero', title: 'Banner đầu trang (Hero)', desc: 'Khu vực đầu tiên khách nhìn thấy, gồm cả thẻ đăng ký khảo sát.',
    fields: [
      { key: 'background_image', label: 'Ảnh nền', type: 'image' },
      { key: 'badge', label: 'Nhãn nhỏ phía trên', type: 'text' },
      { key: 'title_line1', label: 'Tiêu đề – dòng 1', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'title_line2', label: 'Tiêu đề – phần cuối', type: 'text' },
      { key: 'description', label: 'Đoạn mô tả', type: 'textarea' },
      { key: 'value_props', label: 'Các điểm nổi bật (dấu tích)', type: 'list' },
      { key: 'cta_primary', label: 'Nút chính', type: 'text' },
      { key: 'cta_secondary', label: 'Nút phụ', type: 'text' },
      { key: 'stats', label: 'Số liệu thống kê', type: 'stats' },
      { key: 'form_title', label: 'Thẻ đăng ký – tiêu đề', type: 'text' },
      { key: 'form_subtitle', label: 'Thẻ đăng ký – mô tả', type: 'text' },
      { key: 'form_service_label', label: 'Thẻ đăng ký – nhãn chọn dịch vụ', type: 'text', help: 'Danh sách dịch vụ lấy từ mục Dịch vụ (trường "Nhãn ở Hero").' },
      { key: 'form_phone_label', label: 'Thẻ đăng ký – nhãn số điện thoại', type: 'text' },
      { key: 'form_phone_placeholder', label: 'Thẻ đăng ký – gợi ý ô số điện thoại', type: 'text' },
      { key: 'form_submit', label: 'Thẻ đăng ký – nút gửi', type: 'text' },
      { key: 'form_submitting', label: 'Thẻ đăng ký – chữ khi đang gửi', type: 'text' },
      { key: 'trust_left', label: 'Dòng cam kết – trái', type: 'text' },
      { key: 'trust_right', label: 'Dòng cam kết – phải', type: 'text' },
    ],
  },
  {
    key: 'services_section', title: 'Khu Dịch vụ – tiêu đề', desc: 'Phần tiêu đề của khu Dịch vụ. Nội dung từng dịch vụ sửa ở mục "Dịch vụ & bảng giá".',
    fields: [
      { key: 'badge', label: 'Nhãn nhỏ', type: 'text' },
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
      { key: 'price_format', label: 'Mẫu hiển thị giá', type: 'text', help: '{price} sẽ được thay bằng đơn giá. VD: Từ {price}đ / m²' },
      { key: 'card_button', label: 'Nút trên thẻ dịch vụ', type: 'text' },
    ],
  },
  {
    key: 'calculator', title: 'Công cụ tính phí', desc: 'Chữ và cấu hình của khu Ước tính chi phí. Giá & % giảm sửa ở mục "Dịch vụ" và "Tần suất & giảm giá".',
    fields: [
      { key: 'badge', label: 'Nhãn nhỏ', type: 'text' },
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
      { key: 'step1_title', label: 'Bước 1 – tiêu đề', type: 'text' },
      { key: 'service_label', label: 'Nhãn chọn dịch vụ', type: 'text' },
      { key: 'area_label', label: 'Nhãn diện tích', type: 'text' },
      { key: 'area_unit', label: 'Đơn vị diện tích', type: 'text' },
      { key: 'area_min', label: 'Diện tích nhỏ nhất (m²)', type: 'number' },
      { key: 'area_max', label: 'Diện tích lớn nhất (m²)', type: 'number' },
      { key: 'area_step', label: 'Bước kéo (m²)', type: 'number' },
      { key: 'area_default', label: 'Diện tích mặc định (m²)', type: 'number' },
      { key: 'area_hint_min', label: 'Chú thích thanh kéo – trái', type: 'text' },
      { key: 'area_hint_mid', label: 'Chú thích thanh kéo – giữa', type: 'text' },
      { key: 'area_hint_max', label: 'Chú thích thanh kéo – phải', type: 'text' },
      { key: 'frequency_label', label: 'Nhãn tần suất', type: 'text' },
      { key: 'summary_service', label: 'Tóm tắt – dịch vụ', type: 'text' },
      { key: 'summary_rate', label: 'Tóm tắt – đơn giá', type: 'text' },
      { key: 'summary_rate_format', label: 'Tóm tắt – mẫu đơn giá', type: 'text', help: '{rate} = đơn giá' },
      { key: 'summary_discount', label: 'Tóm tắt – ưu đãi', type: 'text' },
      { key: 'summary_standard', label: 'Tóm tắt – khi không giảm giá', type: 'text' },
      { key: 'summary_discount_format', label: 'Tóm tắt – mẫu giảm giá', type: 'text', help: '{pct} = % giảm' },
      { key: 'total_label', label: 'Nhãn tổng chi phí', type: 'text' },
      { key: 'total_note', label: 'Ghi chú tổng chi phí', type: 'text' },
      { key: 'currency', label: 'Đơn vị tiền', type: 'text' },
      { key: 'step2_title', label: 'Bước 2 – tiêu đề', type: 'text' },
      { key: 'name_label', label: 'Nhãn họ tên', type: 'text' },
      { key: 'name_placeholder', label: 'Gợi ý họ tên', type: 'text' },
      { key: 'phone_label', label: 'Nhãn số điện thoại', type: 'text' },
      { key: 'phone_placeholder', label: 'Gợi ý số điện thoại', type: 'text' },
      { key: 'email_label', label: 'Nhãn email', type: 'text' },
      { key: 'email_placeholder', label: 'Gợi ý email', type: 'text' },
      { key: 'date_label', label: 'Nhãn ngày khảo sát', type: 'text' },
      { key: 'address_label', label: 'Nhãn địa chỉ', type: 'text' },
      { key: 'address_placeholder', label: 'Gợi ý địa chỉ', type: 'text' },
      { key: 'notes_label', label: 'Nhãn ghi chú', type: 'text' },
      { key: 'notes_placeholder', label: 'Gợi ý ghi chú', type: 'text' },
      { key: 'submit', label: 'Nút gửi', type: 'text' },
      { key: 'submitting', label: 'Chữ khi đang gửi', type: 'text' },
      { key: 'success_message', label: 'Thông báo gửi thành công', type: 'textarea', help: '{id} = mã báo giá' },
      { key: 'error_required', label: 'Lỗi thiếu thông tin', type: 'text' },
      { key: 'error_failed', label: 'Lỗi gửi thất bại', type: 'text' },
      { key: 'error_network', label: 'Lỗi mất kết nối', type: 'text' },
    ],
  },
  {
    key: 'portfolio', title: 'Khu Dự án – tiêu đề & ảnh trước/sau', desc: 'Tiêu đề và khung so sánh ảnh. Các thẻ dự án sửa ở mục "Dự án".',
    fields: [
      { key: 'badge', label: 'Nhãn nhỏ', type: 'text' },
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
      { key: 'legend_before', label: 'Chú thích "Trước"', type: 'text' },
      { key: 'legend_after', label: 'Chú thích "Sau"', type: 'text' },
      { key: 'before_image', label: 'Ảnh TRƯỚC', type: 'image' },
      { key: 'before_alt', label: 'Mô tả ảnh TRƯỚC (alt)', type: 'text' },
      { key: 'before_badge', label: 'Nhãn trên ảnh TRƯỚC', type: 'text' },
      { key: 'after_image', label: 'Ảnh SAU', type: 'image' },
      { key: 'after_alt', label: 'Mô tả ảnh SAU (alt)', type: 'text' },
      { key: 'after_badge', label: 'Nhãn trên ảnh SAU', type: 'text' },
      { key: 'hint', label: 'Dòng hướng dẫn dưới ảnh', type: 'text' },
    ],
  },
  {
    key: 'testimonials_section', title: 'Khu Đánh giá – tiêu đề', desc: 'Tiêu đề khu Đánh giá. Từng đánh giá sửa ở mục "Đánh giá khách hàng".',
    fields: [
      { key: 'badge', label: 'Nhãn nhỏ', type: 'text' },
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
    ],
  },
  {
    key: 'contact', title: 'Khu Liên hệ', desc: 'Thông tin văn phòng và form gửi lời nhắn.',
    fields: [
      { key: 'badge', label: 'Nhãn nhỏ', type: 'text' },
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'title_highlight', label: 'Tiêu đề – phần tô màu', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
      { key: 'office_title', label: 'Tiêu đề khung thông tin', type: 'text' },
      { key: 'address_label', label: 'Nhãn địa chỉ', type: 'text' },
      { key: 'address', label: 'Địa chỉ', type: 'textarea' },
      { key: 'hotline_label', label: 'Nhãn hotline', type: 'text' },
      { key: 'hotline_text', label: 'Hotline (chữ hiển thị)', type: 'text' },
      { key: 'hotline_tel', label: 'Hotline (số để bấm gọi)', type: 'text', help: 'Chỉ gồm chữ số, VD: 0988123456' },
      { key: 'email_label', label: 'Nhãn email', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'hours_label', label: 'Nhãn giờ làm việc', type: 'text' },
      { key: 'hours', label: 'Giờ làm việc', type: 'text' },
      { key: 'form_title', label: 'Form – tiêu đề', type: 'text' },
      { key: 'name_label', label: 'Form – nhãn họ tên', type: 'text' },
      { key: 'name_placeholder', label: 'Form – gợi ý họ tên', type: 'text' },
      { key: 'phone_label', label: 'Form – nhãn số điện thoại', type: 'text' },
      { key: 'phone_placeholder', label: 'Form – gợi ý số điện thoại', type: 'text' },
      { key: 'email_field_label', label: 'Form – nhãn email', type: 'text' },
      { key: 'email_placeholder', label: 'Form – gợi ý email', type: 'text' },
      { key: 'message_label', label: 'Form – nhãn lời nhắn', type: 'text' },
      { key: 'message_placeholder', label: 'Form – gợi ý lời nhắn', type: 'text' },
      { key: 'submit', label: 'Form – nút gửi', type: 'text' },
      { key: 'submitting', label: 'Form – chữ khi đang gửi', type: 'text' },
      { key: 'success_message', label: 'Thông báo gửi thành công', type: 'text' },
      { key: 'error_required', label: 'Lỗi thiếu thông tin', type: 'text' },
      { key: 'error_network', label: 'Lỗi mất kết nối', type: 'text' },
    ],
  },
  {
    key: 'footer', title: 'Chân trang (Footer)', desc: 'Danh sách "Dịch vụ chính" lấy từ mục Dịch vụ (trường "Nhãn ở Footer").',
    fields: [
      { key: 'about', label: 'Giới thiệu ngắn', type: 'textarea' },
      { key: 'copyright', label: 'Dòng bản quyền', type: 'text' },
      { key: 'services_title', label: 'Tiêu đề cột Dịch vụ', type: 'text' },
      { key: 'links_title', label: 'Tiêu đề cột Liên kết', type: 'text' },
      { key: 'links', label: 'Liên kết nhanh', type: 'links' },
      { key: 'support_title', label: 'Tiêu đề cột Hỗ trợ', type: 'text' },
      { key: 'phone', label: 'Số điện thoại', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'address', label: 'Địa chỉ', type: 'text' },
      { key: 'bottom_note', label: 'Dòng cuối trang', type: 'text' },
      { key: 'back_to_top', label: 'Nút về đầu trang', type: 'text' },
    ],
  },
];

export const COLLECTIONS = {
  services: {
    title: 'Dịch vụ & bảng giá',
    desc: 'Mỗi dịch vụ hiển thị ở 4 nơi: thẻ Dịch vụ, Công cụ tính phí, ô chọn ở Hero, cột Footer. Giá dùng chung cho website và máy chủ.',
    itemTitle: (x) => x.title,
    itemSub: (x) => `${Number(x.pricePerM2).toLocaleString('vi-VN')}đ/m² · phí cơ bản ${Number(x.basePrice).toLocaleString('vi-VN')}đ`,
    empty: { slug: '', title: '', subtitle: '', description: '', pricePerM2: 0, basePrice: 0, icon: 'Scissors', image: '', features: [], calcName: '', heroEmoji: '', heroLabel: '', footerLabel: '', isActive: true },
    fields: [
      { key: 'slug', label: 'Mã dịch vụ (slug)', type: 'text', createOnly: true, help: 'a-z, 0-9, dấu gạch ngang. Dùng để lưu báo giá, không đổi được sau khi tạo.' },
      { key: 'title', label: 'Tên (thẻ Dịch vụ)', type: 'text' },
      { key: 'subtitle', label: 'Tên phụ (dòng nhỏ phía trên)', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea' },
      { key: 'pricePerM2', label: 'Đơn giá (đ/m²)', type: 'number' },
      { key: 'basePrice', label: 'Phí cơ bản (đ)', type: 'number', help: 'Chi phí = (Phí cơ bản + Diện tích × Đơn giá) × (100 − % giảm) / 100' },
      { key: 'icon', label: 'Biểu tượng', type: 'icon' },
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'features', label: 'Đặc điểm (dấu tích)', type: 'list' },
      { key: 'calcName', label: 'Tên ở Công cụ tính phí', type: 'text' },
      { key: 'heroEmoji', label: 'Emoji ở Hero', type: 'text' },
      { key: 'heroLabel', label: 'Nhãn ở Hero', type: 'text' },
      { key: 'footerLabel', label: 'Nhãn ở Footer', type: 'text' },
      { key: 'isActive', label: 'Hiển thị trên website', type: 'bool' },
    ],
  },
  'frequency-options': {
    title: 'Tần suất & giảm giá',
    desc: 'Các lựa chọn tần suất trong Công cụ tính phí và % giảm tương ứng.',
    itemTitle: (x) => x.label,
    itemSub: (x) => (x.discountPct ? `Giảm ${x.discountPct}%` : 'Giá chuẩn'),
    empty: { label: '', discountPct: 0, hint: '', isActive: true },
    fields: [
      { key: 'label', label: 'Tên tần suất', type: 'text' },
      { key: 'discountPct', label: '% giảm', type: 'number' },
      { key: 'hint', label: 'Dòng chú thích nhỏ', type: 'text', help: 'Để trống nếu không muốn hiển thị.' },
      { key: 'isActive', label: 'Hiển thị trên website', type: 'bool' },
    ],
  },
  projects: {
    title: 'Dự án',
    desc: 'Các thẻ dự án bên dưới khung ảnh Trước/Sau.',
    itemTitle: (x) => x.title,
    itemSub: (x) => x.category,
    empty: { category: '', title: '', description: '', image: '', imageAlt: '', isActive: true },
    fields: [
      { key: 'category', label: 'Nhãn (VD: Biệt Thự Ecopark)', type: 'text' },
      { key: 'title', label: 'Tên dự án', type: 'text' },
      { key: 'description', label: 'Mô tả ngắn', type: 'textarea' },
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'imageAlt', label: 'Mô tả ảnh (alt)', type: 'text' },
      { key: 'isActive', label: 'Hiển thị trên website', type: 'bool' },
    ],
  },
  testimonials: {
    title: 'Đánh giá khách hàng',
    desc: 'Các thẻ đánh giá ở khu "Khách hàng nói gì".',
    itemTitle: (x) => x.name,
    itemSub: (x) => `${'★'.repeat(x.stars || 0)} · ${x.role || ''}`,
    empty: { name: '', role: '', content: '', stars: 5, avatar: '', isActive: true },
    fields: [
      { key: 'name', label: 'Tên khách hàng', type: 'text' },
      { key: 'role', label: 'Chức danh / nơi ở', type: 'text' },
      { key: 'content', label: 'Nội dung đánh giá', type: 'textarea' },
      { key: 'stars', label: 'Số sao (1–5)', type: 'number' },
      { key: 'avatar', label: 'Ảnh đại diện', type: 'image' },
      { key: 'isActive', label: 'Hiển thị trên website', type: 'bool' },
    ],
  },
};
